import Head from 'next/head'
import Image from 'next/image'
import Herosection from '../components/Herosection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Its Bakar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Herosection/>
    </div>
  )
}
